# -*- coding: utf-8 -*-
"""
Created on Mon Sep 13 15:37:23 2021

@author: M Shoaib
"""

import numpy as np
import pandas as pd
import seaborn as sns
from plotnine import *
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
df=pd.read_csv('SampleSuperstore.csv')
print(df.info())
df.dropna()

df=df.drop_duplicates()
df.nunique()

###Now lets del unnecessary data
df=df.drop(columns=['Postal Code'],axis=1)
corre=df.corr()
covar=df.cov()
plt.figure(figsize=(16,8))
plt.bar('Sub-Category','Category',data=df)
plt.title('Category vs Sub Category')
plt.xlabel("Sub-Category")
plt.ylabel('Category')
plt.xticks(rotation=45)
plt.show()
df.hist(bins=50,figsize=(20,15))
plt.show();
#the hisogramshowinghatisnotnormal
df['State'].value_counts(())

plt.figure(figsize=(20,15))
sns.countplot(x=df['State'])
plt.xticks(rotation=90)
plt.title("STATE")
plt.show()
Profit_plot = (ggplot(df, aes(x='Sub-Category', y='Profit', fill='Sub-Category')) + geom_col() + coord_flip()
 + scale_fill_brewer(type='div', palette="Spectral") + theme_classic() + ggtitle('Pie Chart'))
"""
Above Pie chart Shows the profit and loss of each and every subcategories.Here from graph we can visualize that "binders" sub-category has suffered the highest amount of loss and also profit amongst all other sub-Categories (For now we can't say that what is the reason it may be because of discounts given on binders subcategory)
Next,"Copiers" Sub-category has gain highest amount of profit with no loss.There are other sub-categories too who are not faced any kind of losses but their profit margins are also low.

Next,Suffering from highest loss is machines.
"""


display(Profit_plot)
sns.set(style="whitegrid")
plt.figure(2, figsize=(20,15))
sns.barplot(x='Sub-Category',y='Profit', data=df, palette='Spectral')
plt.suptitle('Pie Consumption Patterns in the United States', fontsize=16)
plt.show()
figsize=(15,10)
sns.pairplot(df,hue='Sub-Category')
plt.show
"""
From the above plot we can say that Our Data is not Normal and it has some amount of outliers too.

Let's explore more about these outliers by using boxplots.

Ist we'll check Sales from Every Segments of Whole Data
"""
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

state_code = {'Alabama': 'AL','Alaska': 'AK','Arizona': 'AZ','Arkansas': 'AR','California': 'CA','Colorado': 'CO','Connecticut': 'CT','Delaware': 'DE','Florida': 'FL','Georgia': 'GA','Hawaii': 'HI','Idaho': 'ID','Illinois': 'IL','Indiana': 'IN','Iowa': 'IA','Kansas': 'KS','Kentucky': 'KY','Louisiana': 'LA','Maine': 'ME','Maryland': 'MD','Massachusetts': 'MA','Michigan': 'MI','Minnesota': 'MN','Mississippi': 'MS','Missouri': 'MO','Montana': 'MT','Nebraska': 'NE','Nevada': 'NV','New Hampshire': 'NH','New Jersey': 'NJ','New Mexico': 'NM','New York': 'NY','North Carolina': 'NC','North Dakota': 'ND','Ohio': 'OH','Oklahoma': 'OK','Oregon': 'OR','Pennsylvania': 'PA','Rhode Island': 'RI','South Carolina': 'SC','South Dakota': 'SD','Tennessee': 'TN','Texas': 'TX','Utah': 'UT','Vermont': 'VT','Virginia': 'VA','District of Columbia': 'WA','Washington': 'WA','West Virginia': 'WV','Wisconsin': 'WI','Wyoming': 'WY'}
df['state_code'] = df.State.apply(lambda x: state_code[x])
data_of_the_state = df[['Sales', 'Profit', 'state_code']].groupby(['state_code']).sum()


fig = go.Figure(data=go.Choropleth(
    locations=data_of_the_state.index, 
    z = data_of_the_state.Sales, 
    locationmode = 'USA-states', 
    colorscale = 'Reds',
    colorbar_title = 'Sales in USD',
))

fig.update_layout(
    title_text = 'Total State-Wise Sales',
    geo_scope='usa',
    height=800,
)

fig.show()

"""
Now, let us analyze the sales of a few random states from each profit bracket
 (high profit, medium profit, low profit, low loss and high loss) and try to
 observe some crucial trends which might help us in increasing the sales.

We have a few questions to answer here.

1 What products do the most profit making states buy?

2 What products do the loss bearing states buy?

3 What product segment needs to be improved in order to drive the profits higher?
"""



def data_of_the_state_viewer(states):
    """Plots the turnover generated by different product categories and sub-categories for the list of given states.
    Args:
        states- List of all the states you want the plots for
    Returns:
        None
    """
    product_data = df.groupby(['State'])
    for state in states:
        data = product_data.get_group(state).groupby(['Category'])
        fig, ax = plt.subplots(1, 3, figsize = (28,5))
        fig.suptitle(state, fontsize=14)        
        ax_index = 0
        for cat in ['Furniture', 'Office Supplies', 'Technology']:
            cat_data = data.get_group(cat).groupby(['Sub-Category']).sum()
            sns.barplot(x = cat_data.Profit, y = cat_data.index, ax = ax[ax_index])
            ax[ax_index].set_ylabel(cat)
            ax_index +=1
        fig.show()
states = ['California', 'Washington', 'Mississippi', 'Arizona', 'Texas']
data_of_the_state_viewer(states)
x = df.iloc[:, [9, 10, 11]].values

from sklearn.cluster import KMeans
wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', 
                    max_iter = 300, n_init = 10, random_state = 0).fit(x)
    wcss.append(kmeans.inertia_)
sns.set_style("whitegrid") 
sns.FacetGrid(df, hue ="Sub-Category",height = 6).map(plt.scatter,'Sales','Quantity')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], 
            s = 100, c = 'yellow', label = 'Centroids')

plt.legend()
plt.show()
sns.set_style("whitegrid") 
sns.FacetGrid(df, hue ="Sub-Category",height = 6).map(plt.scatter,'Sales','Profit')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], 
            s = 100, c = 'yellow', label = 'Centroids')

plt.legend()
plt.show()
fig, ax = plt.subplots(figsize = (10 , 6))
ax.scatter(df["Sales"] , df["Profit"])
ax.set_xlabel('Sales')
ax.set_ylabel('Profit')
ax.set_title('Sales vs Profit')
plt.show()
"""
From the Above data Visualization and Clustering we can see that in
 Which states and in which Category Sales and profits are High or less,
 We can improve in that States By Providing Discounts in prefered Range
 so that Company and cosumer both will be in profit.So For Deciding that
 Range we have to do some Technical Analysis.One can Do it through Factor
 Analysis,or also can Do it throgh neural networks.¶
One thing to be noted is that while the superstore is incurring 
losses due to giving discounts on its products, they can't stop 
giving discounts of their products. Most of the heavy discounts 
are during festivals, end-of-season and clearance sales which are 
necessary so that the store can make space in their warehouses for
 fresh stock. Also, by incurring small losses, the company gains in 
 the future by attracting more long term customers. Therefore, the small
 losses from discounts are an essential part of company's business
"""
